version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cstracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Expor a porta do DB (opcional, bom para debug)

  web:
    build: .
    container_name: cstracker_web
    command: >
      bash -c "python manage.py migrate && 
               gunicorn cs_trade_portfolio.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Volume para arquivos estáticos
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}

volumes:
  postgres_data:
  static_volume: