services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: cstracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: unless-stopped

  # Serviço da Aplicação Django com Gunicorn
  web:
    build: .
    container_name: cstracker_web
    # O comando agora é executado pelo entrypoint.sh
    command: gunicorn cs_trade_portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: unless-stopped

  # Serviço do Servidor Web Nginx (Proxy Reverso)
  nginx:
    image: nginx:1.25-alpine
    container_name: cstracker_nginx
    ports:
      - "80:80" # Expõe a porta 80 para o tráfego web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: