# Generated by Django 5.0.4 on 2025-08-16 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("buy_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sell_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "buy_source",
                    models.CharField(
                        choices=[
                            ("youpin", "Youpin"),
                            ("skinport", "Skinport"),
                            ("floatdb", "Floatdb"),
                            ("dash_bot", "Dash BOT"),
                            ("dash_p2p", "Dash P2P"),
                            ("buff", "BUFF"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sell_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("youpin", "Youpin"),
                            ("skinport", "Skinport"),
                            ("floatdb", "Floatdb"),
                            ("dash_bot", "Dash BOT"),
                            ("dash_p2p", "Dash P2P"),
                            ("buff", "BUFF"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "date_of_purchase",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("date_sold", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_of_purchase", "item_name"],
            },
        ),
    ]
