# Generated by Django 5.0.4 on 2025-08-17 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0002_trade_owner_trade_trades_trad_owner_i_952381_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
