# Generated by Django 5.2.5 on 2025-08-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Perfil Público"),
        ),
    ]
