# Generated by Django 5.2.5 on 2025-08-23 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0006_alter_profile_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={"ordering": ["-buy_date", "-sell_date", "item_name"]},
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="date_of_purchase",
            new_name="buy_date",
        ),
    ]
