# Generated by Django 5.2.5 on 2025-08-23 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0007_alter_trade_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="date_sold",
            new_name="sell_date",
        ),
    ]
