# Generated by Django 5.2.5 on 2025-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0008_rename_date_sold_trade_sell_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("sell_date"), descending=True, nulls_first=True
                    ),
                    "-buy_date",
                    "item_name",
                ]
            },
        ),
        migrations.AlterField(
            model_name="trade",
            name="buy_source",
            field=models.CharField(
                choices=[
                    ("buff", "BUFF"),
                    ("floatdb", "CSFloat"),
                    ("csmoney", "CS.Money"),
                    ("dash_bot", "Dashskins"),
                    ("dash_p2p", "Dash P2P"),
                    ("p2p", "P2P"),
                    ("rent_skins", "RentSkins"),
                    ("skinport", "Skinport"),
                    ("steam", "Steam"),
                    ("youpin", "Youpin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="sell_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buff", "BUFF"),
                    ("floatdb", "CSFloat"),
                    ("csmoney", "CS.Money"),
                    ("dash_bot", "Dashskins"),
                    ("dash_p2p", "Dash P2P"),
                    ("p2p", "P2P"),
                    ("rent_skins", "RentSkins"),
                    ("skinport", "Skinport"),
                    ("steam", "Steam"),
                    ("youpin", "Youpin"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
