# Generated by Django 5.2.5 on 2025-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0009_alter_trade_options_alter_trade_buy_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="source",
            field=models.CharField(
                choices=[
                    ("buff", "BUFF"),
                    ("floatdb", "CSFloat"),
                    ("csmoney", "CS.Money"),
                    ("dash_bot", "Dashskins"),
                    ("dash_p2p", "Dash P2P"),
                    ("p2p", "P2P"),
                    ("rent_skins", "RentSkins"),
                    ("skinport", "Skinport"),
                    ("steam", "Steam"),
                    ("youpin", "Youpin"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
