# Generated by Django 5.2.5 on 2025-09-03 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0010_investment_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="buy_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trade",
            name="sell_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
