# Generated by Django 5.2.5 on 2025-09-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0012_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="mp_subscription_id",
        ),
        migrations.AddField(
            model_name="subscription",
            name="mp_payment_id",
            field=models.CharField(
                blank=True,
                help_text="ID do pagamento no Mercado Pago",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
