# Generated by Django 5.2.5 on 2025-09-07 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0013_remove_subscription_mp_subscription_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
