# Generated by Django 5.2.5 on 2025-11-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0014_delete_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="source",
            field=models.CharField(
                choices=[
                    ("brskins", "BR Skins"),
                    ("buff", "BUFF"),
                    ("floatdb", "CSFloat"),
                    ("csmoney", "CS.Money"),
                    ("dash_bot", "Dashskins"),
                    ("dash_p2p", "Dash P2P"),
                    ("p2p", "P2P"),
                    ("rent_skins", "RentSkins"),
                    ("skinport", "Skinport"),
                    ("steam", "Steam"),
                    ("youpin", "Youpin"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="buy_source",
            field=models.CharField(
                choices=[
                    ("brskins", "BR Skins"),
                    ("buff", "BUFF"),
                    ("floatdb", "CSFloat"),
                    ("csmoney", "CS.Money"),
                    ("dash_bot", "Dashskins"),
                    ("dash_p2p", "Dash P2P"),
                    ("p2p", "P2P"),
                    ("rent_skins", "RentSkins"),
                    ("skinport", "Skinport"),
                    ("steam", "Steam"),
                    ("youpin", "Youpin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="sell_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brskins", "BR Skins"),
                    ("buff", "BUFF"),
                    ("floatdb", "CSFloat"),
                    ("csmoney", "CS.Money"),
                    ("dash_bot", "Dashskins"),
                    ("dash_p2p", "Dash P2P"),
                    ("p2p", "P2P"),
                    ("rent_skins", "RentSkins"),
                    ("skinport", "Skinport"),
                    ("steam", "Steam"),
                    ("youpin", "Youpin"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
