# Generated by Django 5.2.5 on 2025-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(default="-", max_length=20),
        ),
    ]
