# Generated by Django 5.2.5 on 2025-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("offers", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blacklisted Item",
                "verbose_name_plural": "Blacklisted Items",
                "ordering": ["offers"],
            },
        ),
        migrations.CreateModel(
            name="ScannedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offers", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scanned Item",
                "verbose_name_plural": "Scanned Items",
                "ordering": ["-timestamp"],
            },
        ),
    ]
