# Generated by Django 5.2.5 on 2025-08-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0002_scanneditem_diff"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneditem",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
