# Generated by Django 5.2.5 on 2025-08-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0003_scanneditem_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulerLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Scheduler Log",
                "verbose_name_plural": "Scheduler Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
