# Generated by Django 5.2.5 on 2025-11-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0004_schedulerlogs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Crate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("min_float", models.FloatField(blank=True, null=True)),
                ("max_float", models.FloatField(blank=True, null=True)),
                ("stattrak", models.BooleanField(default=False)),
                ("souvenir", models.BooleanField(default=False)),
                (
                    "special",
                    models.BooleanField(
                        default=False, help_text="Contém '★' no nome (faca ou luva)"
                    ),
                ),
                ("rarity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "real_rarity",
                    models.CharField(
                        blank=True,
                        help_text="Raridade real (Extraordinary -> Covert)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("market_hash_name", models.CharField(db_index=True, max_length=255)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="scanner.collection"
                    ),
                ),
                (
                    "crates",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="scanner.crate"
                    ),
                ),
            ],
        ),
    ]
