# Generated by Django 5.2.5 on 2025-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0005_collection_crate_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="price_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Última vez que o preço foi verificado",
                null=True,
            ),
        ),
    ]
