# Generated by Django 5.2.5 on 2025-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0006_item_price_item_price_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="offers",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
