# Generated by Django 5.2.5 on 2025-11-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeitem",
            name="base_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço Base",
            ),
        ),
    ]
