# Generated by Django 5.2.5 on 2025-11-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_storeitem_base_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeitem",
            name="price",
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Preço Base"
            ),
            preserve_default=False,
        ),
    ]
