# Generated by Django 5.2.5 on 2025-11-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_remove_storeitem_price_alter_storeitem_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="name",
            field=models.CharField(
                default="Minha Loja", max_length=100, verbose_name="Nome da Loja"
            ),
        ),
    ]
