# Generated by Django 5.2.5 on 2025-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0005_storelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="color",
            field=models.CharField(
                default="#0d6efd",
                help_text="Cor principal da sua loja (Hex)",
                max_length=7,
                verbose_name="Cor do Tema",
            ),
        ),
    ]
